import { IMG } from './shared.jsx';


const VENUES = {
  banquet: {
    eyebrow: 'Banquet Lawns',
    title: 'Celebrations Beneath the Open Sky',
    hero: IMG.banquet,
    badges: ['Up to 1000 Guests', 'Open-air', 'Festoon Lighting'],
    introEyebrow: 'The Lawns',
    introTitle: 'Room to Gather, Grandly',
    intro: 'Our flagship lawns stretch across manicured grounds framed by mature trees and warm festoon light. Whether it is a 200-guest sangeet or a 1000-strong reception, the space transforms to your vision — with a dedicated team handling layout, décor and flow.',
    stats: [{ num: 1000, label: 'Seated Guests' }, { num: 12, suffix: 'k', label: 'Sq Ft Lawn' }],
    featuresTitle: 'Designed for Effortless Events',
    features: [
      { icon: 'Lightbulb', title: 'Ambient Lighting', desc: 'Festoon, uplighting and chandeliers tuned to your palette.' },
      { icon: 'Tent', title: 'Flexible Staging', desc: 'Modular stage, dance floor and seating layouts.' },
      { icon: 'Music', title: 'Sound & Power', desc: 'Pro audio, backup power and a discreet green room.' },
    ],
    gallery: [IMG.banquet, IMG.banquet2, IMG.banquet3, IMG.garden],
    galleryTitle: 'Evenings on the Lawn',
    ctaTitle: 'Reserve Your Date',
    ctaText: 'Peak wedding dates book months ahead — share yours and we will hold it while you decide.',
  },
  guesthouse: {
    eyebrow: 'Guest House',
    title: 'Four Boutique Suites for the Inner Circle',
    hero: IMG.suite,
    badges: ['4 Suites', 'Overnight Stay', 'Ensuite'],
    introEyebrow: 'The Suites',
    introTitle: 'Rest Steps From the Celebration',
    intro: 'Four individually styled suites let the couple, family and closest guests stay the night without leaving the estate. Each features a king bed, ensuite bath, and a private view of the gardens — the calm counterpoint to a day of festivities.',
    stats: [{ num: 4, label: 'Suites' }, { num: 8, label: 'Guests' }],
    featuresTitle: 'Considered Comfort',
    features: [
      { icon: 'BedDouble', title: 'King Suites', desc: 'Plush king beds dressed in soft natural linen.' },
      { icon: 'Bath', title: 'Ensuite Baths', desc: 'Rain showers and warm stone finishes.' },
      { icon: 'Coffee', title: 'Morning Service', desc: 'In-suite breakfast and fresh coffee on request.' },
    ],
    gallery: [IMG.suite, IMG.suite2, IMG.suite3, IMG.detail],
    galleryTitle: 'Inside the Suites',
    ctaTitle: 'Add Suites to Your Booking',
    ctaText: 'Suites are offered alongside venue bookings for the wedding party and family.',
  },
  pool: {
    eyebrow: 'Swimming Pool',
    title: 'A Crystal-Blue Pool & Jacuzzi',
    hero: IMG.pool,
    badges: ['Pool & Jacuzzi', 'Sun Loungers', 'Poolside Service'],
    introEyebrow: 'The Pool',
    introTitle: 'Daytime Ease, Evening Glamour',
    intro: 'A temperature-controlled pool and bubbling jacuzzi anchor the leisure side of the estate. Framed by palms, loungers and a poolside bar, it hosts relaxed daytime gatherings, pool parties and cocktail hours as the sun goes down.',
    stats: [{ num: 25, suffix: 'm', label: 'Pool Length' }, { num: 6, label: 'Seat Jacuzzi' }],
    featuresTitle: 'Poolside, Perfected',
    features: [
      { icon: 'Waves', title: 'Heated Pool', desc: 'Temperature-controlled for year-round swims.' },
      { icon: 'Sun', title: 'Lounger Deck', desc: 'Sun loungers, parasols and cabana seating.' },
      { icon: 'Martini', title: 'Poolside Bar', desc: 'Cocktails, mocktails and snacks served to your chair.' },
    ],
    gallery: [IMG.pool, IMG.pool2, IMG.jacuzzi, IMG.garden],
    galleryTitle: 'By the Water',
    ctaTitle: 'Host a Pool Party',
    ctaText: 'The pool deck can be booked for daytime events and cocktail evenings.',
  },
  gazebo: {
    eyebrow: 'Garden Gazebo',
    title: 'An Intimate Gazebo in the Gardens',
    hero: IMG.gazebo,
    badges: ['Vows & Mehndi', 'Golden Hour', 'Floral Ready'],
    introEyebrow: 'The Gazebo',
    introTitle: 'Where the Smallest Moments Live',
    intro: 'Tucked among the gardens, the gazebo is built for the intimate moments — vows, a mehndi ceremony, golden-hour portraits or a quiet proposal. Its open timber frame takes florals beautifully and catches the warmest light of the day.',
    stats: [{ num: 40, label: 'Seated' }, { num: 360, suffix: '°', label: 'Garden Views' }],
    featuresTitle: 'Made for Intimacy',
    features: [
      { icon: 'Flower2', title: 'Floral Frame', desc: 'Timber structure designed for drapes and blooms.' },
      { icon: 'Camera', title: 'Portrait Light', desc: 'Positioned for soft golden-hour photography.' },
      { icon: 'Heart', title: 'Ceremony Ready', desc: 'Perfect for vows, mehndi and proposals.' },
    ],
    gallery: [IMG.gazebo, IMG.gazebo2, IMG.detail, IMG.garden],
    galleryTitle: 'In the Garden',
    ctaTitle: 'Plan an Intimate Ceremony',
    ctaText: 'Pair the gazebo with the lawns for a ceremony-and-reception flow.',
  },
  restaurant: {
    eyebrow: 'Outdoor Restaurant',
    title: 'Open-Air Dining Under the Stars',
    hero: IMG.restaurant,
    badges: ['Multi-Cuisine', 'Live Counters', 'Alfresco'],
    introEyebrow: 'The Restaurant',
    introTitle: 'A Feast in the Fresh Air',
    intro: 'Our open-air restaurant serves a curated multi-cuisine menu with live counters and à-la-minute grills. Dine beneath the stars as part of an event, or book the space for a private celebration — our chefs tailor every menu to the occasion.',
    stats: [{ num: 120, label: 'Covers' }, { num: 8, label: 'Live Counters' }],
    featuresTitle: 'From Our Kitchen',
    features: [
      { icon: 'ChefHat', title: 'Live Counters', desc: 'Tandoor, grills and global stations made to order.' },
      { icon: 'Wine', title: 'Curated Bar', desc: 'Wines, cocktails and signature mocktails.' },
      { icon: 'Leaf', title: 'Seasonal Menus', desc: 'Menus built around fresh, seasonal produce.' },
    ],
    gallery: [IMG.restaurant, IMG.restaurant2, IMG.food, IMG.detail],
    galleryTitle: 'At the Table',
    ctaTitle: 'Design Your Menu',
    ctaText: 'Share your guest count and tastes — our chefs will propose a tailored menu.',
  },
};

export { VENUES };
